#!/bin/sh

sudo apt update -y
sudo apt upgrade -y

./remove_cursor &

reload=$((60 * 60 * 3))

while :
do
	echo "pi client_manager: Refreshing"
	git fetch origin
	git reset --hard origin/main

	./client

	sleep "$reload"
done
