#!/bin/sh

reload=10

while :
do
	echo "pi client: Refreshing"
	git pull

	# --guest: Open guest window (no history when closing/opening)
	# Alternative: --window-position and --window-size

	# --kiosk: Start in fullscreen and do not show ~"press f11 to exit
	# fullscreen" dialog

	# --force-device-scale-factor: UI zoom

	# Full list: https://peter.sh/experiments/chromium-command-line-switches/

	endpoint=$(cat ./endpoint)
	killall chromium
	chromium \
		--guest \
		--kiosk \
		--force-device-scale-factor=1.3 \
		"$endpoint" &

	sleep "$reload"
done
