#!/bin/sh

endpoint="http://10.242.207.207:17860/"

killall chromium

# --guest: Open guest window (no history when closing/opening)
# Alternative: --window-position and --window-size

# --kiosk: Start in fullscreen and do not show ~"press f11 to exit
# fullscreen" dialog

# --force-device-scale-factor: UI zoom

# Full list: https://peter.sh/experiments/chromium-command-line-switches/

endpoint=$(cat ./endpoint)
chromium \
	--guest \
	--kiosk \
	--force-device-scale-factor=3 \
	"$endpoint" &
