#!/bin/sh
# See https://github.com/a13xrzteach/a13xrzteach.github.io/blob/main/README.md

log() {
	echo "pi server: $1"
}

port=17860

cd ..

log "Serving $PWD on port $port"
log "Private IP address: $(ip -j route get 1.2.3.4 | jq -r -M '.[0].prefsrc')"
echo

if [ -d env ]
then
	. env/bin/activate
else
	virtualenv env
	. env/bin/activate
	pip install -r requirements.txt
fi

uvicorn monitor:app --reload --host 0.0.0.0 --port $port
