#!/bin/sh

log() {
	echo "pi server: $1"
}

if ! ping -c 1 google.com > /dev/null
then
	log "No internet"
	exit 1
fi

# Update https://github.com/a13xrzteach/a13xrzteach.github.io/blob/main/pi/endpoint
port=17860

cd ..

log "Serving $PWD on port $port"
log "Private IP address: $(ip -j route get 1.2.3.4 | jq -r -M '.[0].prefsrc')"
echo

darkhttpd . --port $port
