#!/bin/sh

# Be very careful about updating this startup script. If it changes while a
# monitor is running it, it could malfunction and get stuck in an infinite loop,
# requiring manual intervention.

if echo "$0" | grep -q "^/"
then
	dir=${0%/*}
	echo "startup: cd $dir"
	cd "$dir"
fi

echo "startup: pulling"

# A literal git pull would break if you accidentally commit something locally
# (which has happened multiple times; Michael is a clown)
git fetch origin
git reset --hard origin/main

echo "startup: planning reboot"

reboot="$(mktemp -u).$(date +%s)"
cp ./plan_reboot "$reboot"
"$reboot" &

sleep 2

echo "startup: starting manager"

manager="$(mktemp -u).$(date +%s)"
cp ./client_manager "$manager"
"$manager"

echo "startup: manager failed"

# Manager exited early for some reason (error)
# It's fine if this is just run directly
./plan_reboot

echo "startup: planned reboot failed"

fail="https://www.google.com/finance/quote/NVDA:NASDAQ"
chromium --guest "$fail" &

# plan_reboot also exited instead of rebooting
sleep 180

killall chromium
reboot

sleep 180

# Last effort: restart (because clearly rebooting doesn't work)
./startup
